=== org.opendaylight.eclipse.setup

_TODO get a proposed gerrit into eclipse.org so that one can actually use it like this (once it is end-user ready for initial beta testers):_

OpenDaylight has Oomph, and you can set up an Eclipse-based development workspace for OpenDaylight projects by:

1. Downloading the Eclipse Installer from https://www.eclipse.org/downloads/ and starting it.
2. On the initial page, click on the *Switch to advanced mode* button in the top right.
3. On the *Product* page, select *Eclipse IDE for Java Developers*.
4. On the *Projects* page, collapse the *Eclipse Projects* to scroll down to the *OpenDaylight Projects* and double-click those of interest to you.
5. Choose your preferred installation settings on the *Variables* page.
6. Finish the wizard and watch how your development environment is being assembled, courtesy of Oomph.

This project fully automates the way too many manual steps currently described on
https://wiki.opendaylight.org/view/GettingStarted:_Eclipse, in order for anyone to get easily started
successfully hacking on https://www.opendaylight.org quickly.

This is implemented used an Eclipse "Oomph" workspace set up model, see http://www.eclipse.org/oomph

By default, it will git clone the repos of all projects you clicked into your new ${installation.location/git}.
If you already have OpenDaylight projects git clone, then on the "Variables" step of the Eclipse Installer,
just click [X] Show all variables, and replace the "Git clone location:" variable which defaults to
"${installation.location/git/}${@id.remoteURI|gitRepository}" by something like 
"/absolute/path/where/you/keep/your/opendaylight/clones/${@id.remoteURI|gitRepository}".

This is a protoype which I'm starting on https://github.com/vorburger/opendaylight-eclipse-setup 
just because it's easier for me to maintain it here for now.  If this becomes used by others,
I expect we'll move it to https://git.opendaylight.org  
TODO which repo, new or inside an existing one? 

Michael Vorburger @ work @ Red Hat
April 2016


==== Implementation

===== Project List

Please note that the projects/*.setup are auto-generated by the generator/src/**/ProjectsSetupGenerator.xtend
baed on the generator/projects.txt list.  Those  projects/*.setup models should thus never be hand-edited
(contrary to the root org.opendaylight.projects.setup); instead fix the template in the ProjectsSetupGenerator
if anything could be improved, and re-run the generator.
